# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from inference.proto import inference_pb2 as inference_dot_proto_dot_inference__pb2


class AsyncInferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenSession = channel.unary_unary(
                '/remote_inference.v1.AsyncInference/OpenSession',
                request_serializer=inference_dot_proto_dot_inference__pb2.OpenSessionRequest.SerializeToString,
                response_deserializer=inference_dot_proto_dot_inference__pb2.OpenSessionResponse.FromString,
                )
        self.SendObservation = channel.unary_unary(
                '/remote_inference.v1.AsyncInference/SendObservation',
                request_serializer=inference_dot_proto_dot_inference__pb2.Observation.SerializeToString,
                response_deserializer=inference_dot_proto_dot_inference__pb2.ObservationAck.FromString,
                )
        self.GetActionChunk = channel.unary_unary(
                '/remote_inference.v1.AsyncInference/GetActionChunk',
                request_serializer=inference_dot_proto_dot_inference__pb2.ActionRequest.SerializeToString,
                response_deserializer=inference_dot_proto_dot_inference__pb2.ActionChunk.FromString,
                )
        self.CloseSession = channel.unary_unary(
                '/remote_inference.v1.AsyncInference/CloseSession',
                request_serializer=inference_dot_proto_dot_inference__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class AsyncInferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OpenSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendObservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActionChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsyncInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenSession': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=inference_dot_proto_dot_inference__pb2.OpenSessionRequest.FromString,
                    response_serializer=inference_dot_proto_dot_inference__pb2.OpenSessionResponse.SerializeToString,
            ),
            'SendObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.SendObservation,
                    request_deserializer=inference_dot_proto_dot_inference__pb2.Observation.FromString,
                    response_serializer=inference_dot_proto_dot_inference__pb2.ObservationAck.SerializeToString,
            ),
            'GetActionChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActionChunk,
                    request_deserializer=inference_dot_proto_dot_inference__pb2.ActionRequest.FromString,
                    response_serializer=inference_dot_proto_dot_inference__pb2.ActionChunk.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=inference_dot_proto_dot_inference__pb2.CloseSessionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remote_inference.v1.AsyncInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AsyncInference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OpenSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote_inference.v1.AsyncInference/OpenSession',
            inference_dot_proto_dot_inference__pb2.OpenSessionRequest.SerializeToString,
            inference_dot_proto_dot_inference__pb2.OpenSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote_inference.v1.AsyncInference/SendObservation',
            inference_dot_proto_dot_inference__pb2.Observation.SerializeToString,
            inference_dot_proto_dot_inference__pb2.ObservationAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActionChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote_inference.v1.AsyncInference/GetActionChunk',
            inference_dot_proto_dot_inference__pb2.ActionRequest.SerializeToString,
            inference_dot_proto_dot_inference__pb2.ActionChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/remote_inference.v1.AsyncInference/CloseSession',
            inference_dot_proto_dot_inference__pb2.CloseSessionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
